# Super user permission and Docker required.
sudo: required
services:
 - docker

before_install:
 - docker build -t nanraj50/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true nanraj50/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-101421875185"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$SECRET_ACCESS_KEY"
