# Super user permission and Docker required.
sudo: required
services:
 - docker

before_install:
 - docker build -t nanraj50/docker-react -f Dockerfile.dev .

script:
 - docker run nanraj50/docker-react npm test -- --coverage